apiVersion: v1
kind: Pod
metadata:
  name: db2
spec:
  containers:
  - name: db2-container
    image: ibmcom/db2
    securityContext:
      privileged: true
    env:
    - name: LICENSE
      value: "accept"
    - name: DB2INST1_PASSWORD
      value: "changeit"
    - name: DBNAME
      value: "MIKA"
